### ISSUE TITLE
Add WM feature

### ISSUE THREAD

**Issue by Rstar284** [Nekurone/double-pendulum-ascii#18]
I use i3wm, and it seems that theres only a DE function, which returns Generic
Mabye change the line to `WM/DE:` or make a seperate line stating the wm currently running

**Comment by X0RBYT3** [comment]
I looked into ways of trying to grab the WM, and as far as I can tell there's no 'simple' way to try for WM on py that isn't essentially trial and error of each one.

That being said, I support the change to WM/DE until I (or someone much smarter than myself) understands the neofetch code well enough to translate it into python

**Comment by Rstar284** [comment]
Thanks :)
